<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body class="clean-body u_body"
      style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #EFEDFA;color: #190E88">
<table style="font-family:arial,helvetica,sans-serif;"
       role="presentation"
       cellpadding="0"
       cellspacing="0"
       width="100%"
       border="0">
    <tbody>
    <tr>
        <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;"
            align="left">
            <div style="font-size: 14px; line-height: 140%; text-align: left; word-wrap: break-word;">
                <p style="line-height: 140%;">Hello ${name},</p>
                <p style="line-height: 140%;">Welcome to ${nnpName}. Your user id is ${userId}. Please try to log in at ${nnpPortalURL}. Please get in touch with support at ${nnpEmail} in case any help is required.</p>
                <p style="line-height: 140%;">Regards,</p>
                <p style="line-height: 140%;">${nnpAdmin} </p>
            </div>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>
